### PR TITLE
Update android packages

### PR DESCRIPTION
**Pull request by guillaume-roy**
* The actual versions of packages are incompatible with other nativescript plugins at build time.
 * Especially the `+` notation : `compile 'com.google.android.gms:play-services-analytics:+'`
 * In my case the issue was with @EddyVerbruggen 's nativescript-plugin-firebase plugin.
* It seems that the latest version of `com.android.tools.build:gradle` is `2.1.0` but when nativescript-cli creates android platform the version is `1.5.0` and in your plugin it's `2.0.0-beta6`. In doubt, i didn't change it, it's just for your information.

### CODE REVIEW

**Comment by guillaume-roy** [comment]
Hello ?

**Comment by sitefinitysteve** [comment]
I'll merge today

**Comment by guillaume-roy** [comment]
Thanks !

**Comment by sitefinitysteve** [comment]
Updated on npm now

Sorry about this, HONESTLY... I saw the email, but didn't see it was a PR :)

**Comment by guillaume-roy** [comment]
No problem. I remembered that yesterday.

**Pull request merged**
